version: "3.7"

services:
  postgres:
    image: "postgres:14-alpine"
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    container_name: postgres-recipemountain
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.dev
    image: backend-recipemountain-dev
    init: true
    links:
      - "postgres:database"
    env_file:
      - postgres.env
      - backend.env
    volumes:
      - ./services/backend:/app
    ports:
      - "5000:5000"
    container_name: backend-recipemountain-dev
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.dev
    image: frontend-recipemountain-dev
    links:
      - backend
    volumes:
      - ./services/frontend:/app
    ports:
      - "8080:8080"
    container_name: frontend-recipemountain-dev

volumes:
  postgres:
