version: "3.9"

services:
  postgres:
    image: "postgres:14.0-alpine"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=test
    ports:
    - "5432:5432"
    container_name: "postgres"
    volumes:
    - postgres:/var/lib/postgresql/data
  
  backend:
    build: ./services/backend
    links:
      - "postgres:database"
    environment:
      - DB_HOST=database 
      - DB_URL=postgres://user:pass@database:5432/test
    ports:
      - "5000:5000"
    container_name: "backend"
    depends_on:
      - postgres
  
  frontend:
    build: ./services/frontend
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider # required for node to start, bug with current version of node 
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - "8080:8080"

volumes:
  postgres:
    name: postgres
