version: "3.9"

services:
  networks:
  default:
    name: recipemountain-network
  postgres:
    image: "postgres:14.0-alpine"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=test
    ports:
    - "5432:5432"
    container_name: "postgres-recipemountain"
    volumes:
    - postgres:/var/lib/postgresql/data
  
  backend:
    build: ./services/backend
    links:
      - "postgres:database"
    environment:
      - PROJECT_NAME=RecipeMountain
      - FIRST_SUPERUSER=admin@example.com
      - FIRST_SUPERUSER_PASSWORD=admin
      - POSTGRES_SERVER=database:5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=test
    ports:
      - "5000:5000"
    container_name: "backend-recipemountain"
    depends_on:
      - postgres
  
  frontend:
    build: ./services/frontend
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider # required for node to start, bug with current version of node 
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - "8080:8080"
    container_name: "frontend-recipemountain"

volumes:
  postgres:
    name: postgres
